# Generated by Django 3.0.3 on 2020-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.IntegerField()),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_sal', models.FloatField()),
                ('emp_dept', models.CharField(max_length=64)),
                ('emp_add', models.CharField(max_length=128)),
            ],
        ),
    ]
